### Horizon based theme switching ###
alias: 'Daylight automatic theme switching'
  trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: sun.sun
      to: above_horizon
    - platform: state
      entity_id: sun.sun
      to: below_horizon
  action:
    - service_template: frontend.set_theme
      data_template:
      name: >
        {% if states.sun.sun.state == "above_horizon" %}
          Light - Light Red
        {% else %}
          Dark - Light Red
        {% endif %}

### HA Update Notification ###
alias: 'Update Available Notifications'
trigger:
  platform: state
  entity_id: updater.updater
action:
  service: notify.notify
  data:
    message: 'Update for Home Assistant is available.'

### Owntracks Refresh ###
alias: "Owntracks Refresh"
trigger:
  - platform: time
    minutes: '/15'
    seconds: 0
action:
  service: script.refresh_devices

# Turn off lights when everybody leaves the house
  - alias: 'Away Mode'
    trigger:
      platform: state
      entity_id: group.all_devices
      to: 'not_home'
    action:
      service: light.turn_off
      entity_id: group.all_lights

### Zigbee2MQTT Automations ###
- alias: Zigbee2mqtt Log Level
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_select.zigbee2mqtt_log_level
      to: debug
    - platform: state
      entity_id: input_select.zigbee2mqtt_log_level
      to: warn
    - platform: state
      entity_id: input_select.zigbee2mqtt_log_level
      to: error
    - platform: state
      entity_id: input_select.zigbee2mqtt_log_level
      to: info
  action:
    - service: mqtt.publish
      data:
        payload_template: '{{ states(''input_select.zigbee2mqtt_log_level'') }}'
        topic: zigbee2mqtt/bridge/config/log_level

- id: enable_zigbee_join
  alias: Enable Zigbee joining
  hide_entity: true
  trigger:
    platform: state
    entity_id: input_boolean.zigbee_permit_join
    to: 'on'
  action:
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/bridge/config/permit_join
      payload: 'true'
  - service: timer.start
    data:
      entity_id: timer.zigbee_permit_join

- id: disable_zigbee_join
  alias: Disable Zigbee joining
  hide_entity: true
  trigger:
  - entity_id: input_boolean.zigbee_permit_join
    platform: state
    to: 'off'
  action:
  - data:
      payload: 'false'
      topic: zigbee2mqtt/bridge/config/permit_join
    service: mqtt.publish
  - data:
      entity_id: timer.zigbee_permit_join
    service: timer.cancel

- id: disable_zigbee_join_timer
  alias: Disable Zigbee joining by timer
  hide_entity: true
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.zigbee_permit_join
  action:
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/bridge/config/permit_join
      payload: 'false'
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.zigbee_permit_join
