homeassistant:
  # Name of the location where Home Assistant is running
  name: Wakanda
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Temperature unit: C for Celsius, F for Fahrenheit
  temperature_unit: F
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles
  # Customization file
  customize: !include customize.yaml
  customize_glob: !include globals.yaml
#  whitelist_external_dirs:
#    - /config/www/custom_ui/floorplan/images

#########################
### Frontend          ###
#########################

# Enables the frontend
frontend:
  javascript_version: latest
  themes: !include themes.yaml
  extra_html_url:
    - /local/custom_ui/state-card-aftership.html
    - /local/custom_ui/custom-weather-animated.html
    - /local/custom_ui/state-card-hline.html
    - /local/hass-fontawesome-solid.html
    - /local/hass-fontawesome-regular.html
    - /local/hass-fontawesome-brands.html
  extra_html_url_es5:
    - /local/custom_ui/custom-weather-animated.html
    - /local/custom_ui/state-card-hline_es5.html


### Component Panels ###


#########################
###     Web Access    ###
#########################

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  api_password: !secret password
  base_url: !secret base_url
#  ssl_certificate: !secret ssl_certificate
#  ssl_key: !secret ssl_key
  cors_allowed_origins:
    - https://google.com
    - https://www.home-assistant.io
    - https://reformedreality.com
    - http://reformedreality.com
  ip_ban_enabled: True
  login_attempts_threshold: 3

### MQTT ###


##################################
# Checks for available updates   #
##################################
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

### Custom updater ###
#custom_updater:
#component_urls:


#########################
### Native Components ###
#########################

# Enables configuration UI
config:

# Discover some devices automatically
discovery:

# Show links to resources in log and frontend
#introduction:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Provides a service to open URLs in the default browser on the host machine.
browser:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:
  exclude:
    entities:
      - sensor.time
      - sensor.date
      - sensor.ups_status_date
      - sensor.time
      - sensor.date
      - sensor.ha_uptime
      - py.warnings
    domains:
      - sun
# Log Viewer
logger:
  default: info

# Recorder
recorder:
  purge_keep_days: 14
  purge_interval: 7
  db_url: !secret mariadb
  exclude:
    domains:
      - camera
      - media_player
      - sun
      - moon
    entities:
      - sensor.time
      - sensor.date
      - sensor.time_utc
      - sensor.internet_time
      - binary_sensor.period_of_day
      - sensor.season
      - weather.current
      - sensor.ha_uptime

logger: !include logger.yaml
recorder: !include recorder.yaml

### InfluxDB - for Grafana ###


# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction


# Text to speech


# Zeroconf/Avahi/Bonjour
zeroconf:

# UPNP
upnp:

# FFmpeg
ffmpeg:

# API
api:

# Python Scripts
python_script:

# Home Assistant Cloud
cloud:
### Google Assistant Actions ###
  google_actions:
    filter:
      include_domains:
        - light
        - group
        - input_boolean
        - scene
        - script
        - switch
        - fan
        - cover
        - media_player
        - climate
      exclude_entities:
        - group.all_lights
        - media_player.falcon
        - media_player.redwing
        - media_player.storm
        - media_player.vixen
        - media_player.whole_home_music
        - remote.harmony_hub
        - media_player.pn58c8000_samsung_dtv_rcr
### Amazon Alexa Skills ###


files:

pvoutput:

httpreq:
############################
### 3rd Party Components ###
############################

# IFTTT


### OwnTracks ###


# Enable DialogFlow
dialogflow:



### Nest ###


### Sonoff/eWelink Native ###


### Habitca ###
habitica:
  - api_user: !secret habit_id
    api_key: !secret habit_key
    name: Ozone

### Dominos Pizza ###
#dominos:
#  country_code: !secret country_code
#  first_name: !secret firstname
#  last_name: !secret lastname
#  email: !secret email
#  phone: !secret phone
#  address: !secret address

### Generic Thermostat ###


### Join ###
joaoapps_join:
  - name: Androids
    device_id: group.android,group.pc
    api_key: !secret join_api

### Google Calendar ###
google:
  client_id: !secret google_id
  client_secret: !secret google_secret

### Earthquakes ###
geo_location:
  - platform: usgs_earthquakes_feed
    feed_type: 'past_day_all_earthquakes'
    radius: 50
    minimum_magnitude: 0.0

### Microsoft Face ###

#########################
###     Includes      ###
#########################
#homekit: !include homekit.yaml
#group: !include_dir_merge_named group
#sensor: !include_dir_merge_list sensor
#binary_sensor: !include_dir_merge_list binary_sensor
#automation: !include_dir_merge_list automation
#scene: !include_dir_merge_list scene
#switch: !include_dir_merge_list switch
#script: !include_dir_merge_named script
#input_boolean: !include_dir_merge_named input_boolean
#shell_command: !include_dir_merge_named shell_command
#zone: !include_dir_merge_name_name zones
#input_datetime: !include input_datetimes.yaml
#input_number: !include input_numbers.yaml
#input_select: !include input_selects.yaml
#input_text: !include input_texts.yaml
#alarm_control_panel: !include alarm_control_panels.yaml
#camera: !include cameras.yaml
#cover: !include covers.yaml
#battery: !include batteries.yaml
#light: !include lights.yaml
#python_scripts: !include_dir_named python_scripts
#shell_scripts:  !include_dir_named shell_scripts
#timer: !inclune timers.yaml
#variable: !include variables.yaml
#notify: !include notifiers.yaml
#media_player: !include media_players.yaml
#theme: !include_dir_merge_list theme
#fan: !include fans.yaml

