### TP-Link Kasa Switches ###
- platform: tplink
  host: !secret air_filter
- platform: tplink
  host: !secret dehumidifier

### Switchmate Light Toggle ###
- platform: switchmate
  name: Patio
  mac: !secret patio
  flip_on_off: false
