### TP-Link Kasa Switches ###
- platform: tplink
  host: !secret air_filter
- platform: tplink
  host: !secret dehumidifier

### Switchmate Light Toggle ###
- platform: switchmate
  name: Patio
  mac: !secret patio
  flip_on_off: false
- platform: switchmate
  name: Kitchen Fan
  mac: !secret kitchen_fan
  flip_on_off: false
### Wake on LAN ###
- platform: wake_on_lan
  mac_address: !secret bishop_mac
  name: "Bishop WOL"
  host: "!secret bishop_ip"


### HA-Dockermon ###
#  - platform: hadockermon
#    host: 192.168.1.50
#    port: 8126
#    containers:
#      - 'NGINX'
#      - 'ha-dockermon'

### Zigbee2MQTT Switch for enabling joining ###
#  - platform: mqtt
#    name: "Zigbee2mqtt Main join"
#    state_topic: "zigbee2mqtt/bridge/config/permit_join"
#    command_topic: "zigbee2mqtt/bridge/config/permit_join"
#    payload_on: "true"
#    payload_off: "false"
